# Generated by Django 3.0.4 on 2020-04-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('image', models.FilePathField(path='/img')),
                ('long_description', models.TextField()),
                ('project_link', models.URLField(max_length=250)),
            ],
        ),
    ]
