# Generated by Django 3.0.4 on 2020-04-15 06:52

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='long_description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
